### ISSUE TITLE
Add service layer for club

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#103]
### Tasks

- [x] Create a service class for club resource and move business logic inside it
- [x] Create a data provider for club related tests
- [x] Update tests for resource class and add tests for service class by leveraging the test data provider 
- [x] Update player creation logic to use the club service instead of the club DAO
