### ISSUE TITLE
Modify Club entity to store Funds instead of Income and Expenditure

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#104]
### Tasks

- [x] Make `income` and `expenditure` properties nullable so that they are read-only
- [x] Add a `funds` property to track a club's total financial wealth at any time. **NOTE**: this can only be set during club creation. Thereafter, it can transitively be updated when income and expenditure properties are updated via player transfers, shirt sales, etc.
- [x] `transferBudget` and `wageBudget` stay as is. But will be derived on the basis of the `funds` property on the client.
