### ISSUE TITLE
Update club creation form to match server changes

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#105]
### Tasks
- [x] Remove the _Transfer Budget_ and _Wage Budget_ fields in the form and in tests (if any)
- [x] Add a _Manager Funds_ field in the form.
- [x] Add a slider element in the form to determine transfer and wage budget break up. Set their values on the basis of the percentage break up before posting the data to the server.
