### ISSUE TITLE
Add validation layer

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#108]
### Tasks

- [x] Explore how to allow the service layer to accumulate validations on the basis of business logic and then the resource layer can return appropriate response codes and error messages on the basis of it.
- [x] Consider adding warning and error level validations.
- [x] Add the classes needed for implementing the validation layer. Add unit tests.
- [x] Integrate with existing classes.
