### ISSUE TITLE
Add _belongs-to_ checks to DELETE endpoints for resources

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#109]
### Tasks

- [ ] For club resource, check if the club id requested to be deleted belongs to the user making the request (use the User auth principal)
- [ ] For player resource, fetch a list of IDs for the clubs belonging to a user (available via auth principal) and verify that the club id (present on the player entity) for the player being deleted is present in that list. Can be implemented as a DAO method or service method.
- [ ] For match performance, the same check as with the player but with an added level of nesting as the player data associated with the match performance entity would have to be fetched as well.
