### ISSUE TITLE
Add country flag URL in SquadPlayer entity

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#112]
### Tasks

- [x] Add property on SquadPlayer entity.
- [x] Set the value via the country code metadata dictionary when endpoint is hit.
- [x] Remove `flagCodes.json` usage in client.
