### ISSUE TITLE
Add lookup endpoints for static data required from backend

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#114]
### Tasks
- [ ] Add a Lookup resource with GET endpoints for the various data required on the client.
- [ ] Explore how to handle this use-case with react-query. Ideally, we should not need to call this after app load.
- [ ] Replace the dummy data placeholders in the client to call the look-up endpoints instead.
