### ISSUE TITLE
Migrate from Apexcharts to Recharts

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#136]
### Context
Using ApexCharts is slowly becoming a headache. It has very poor documentation and now, turns out it doesn't work with `react-testing-library`. Recharts, on the other hand, has a very modular API with good documentation and works with `react-testing-library` (renders without any errors at the very least). 

### Tasks
- [x] Install `recharts` as a dependency. 
- [x] Replace all existing usages of `react-apexcharts` with `recharts` charts
- [x] Add tests to some components like PlayerProgressionView and PlayerComparisonView which wasn't possible with `react-apexcharts` before.
- [x] Remove workaround added in SquadHubView component due to the `react-apexcharts` issue.
- [x] Remove `react-apexcharts` dependency.

### Acceptance criteria
* All existing charts should have the same behavior as before.
* Any workarounds introduced due to the shortcomings of the `react-apexcharts` library should be removed.
* UTs should be added for chart heavy components.
