### ISSUE TITLE
Enhance create club endpoint to allow users to upload the club logo image

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#141]
## Tasks
- [ ] Add `dropwizard-forms` dependency
- [ ] Add _MultiPartBundle_ in the initialize method of the _Application_ file.
- [ ] Encapsulate the file processing logic in a service, including any filtering on the basis of size or file type.
- [ ] Enhance the create club endpoint to include multi-part form data fields
- [ ] Update tests, if possible.

## Acceptance criteria
* User should be able to upload an image for the club logo when creating a club. (API endpoint only)
