### ISSUE TITLE
Integrate client with server code to upload the club logo image when creating a club.

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#144]
## Context
Connect the server-side changes with the client-side changes and test end-to-end the creation of a club including the uploading and saving of the club logo image.

## Tasks
- [x] Update add club endpoint in club client to process multi-part form data and hit the updated create club endpoint on the server.
- [x] Update `react-query` query if need be.
- [x] Manually verify it works.
- [x] Add Unit and API tests

## Acceptance criteria
* User can successfully create a new club by filling out its details including uploading an image for the club logo.
