### ISSUE TITLE
Enhance update club endpoint to allow users to update the club logo by uploading a different image.

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#145]
## Tasks
- [x] Enhance the update club endpoint to accommodate club logo image upload as well.
- [x] Add any validations applicable for updating the club logo image.
- [ ] Add UTs and API tests.

## Acceptance criteria
* User is able to (through cURL calls) update the club details including the club logo.
