### ISSUE TITLE
Integrate client with server code to upload the club logo image when updating a club.

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#146]
## Context
Connect the server-side changes with the client-side changes and test end-to-end the updating of club details including the club logo image.

## Tasks
- [ ] Modify the update club endpoint in the club client to process multi-part form data and hit the enhanced update club endpoint on the server.
- [ ] Update `react-query` query if need be.
- [ ] Manually verify it works.
- [ ] Add Unit and API tests

## Acceptance criteria
* User can successfully update an existing club by filling out its details including uploading a new image for the club logo.

**Comment by Spider101** [comment]
Closing this for now because updating the club is not implemented in the client yet. Will reopen when ready.
