### ISSUE TITLE
Create well defined DAO layer

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#151]
### Context
The DAO layer in the application is strongly coupled with the couchbase implementation which makes it difficult to swap it out with other implementations if the need arises.

### Tasks
- [x] Define the general API for manipulating the different domain entities.
- [x] Implement a couchbase DAO for the different entities following the aforementioned API
- [x] Implement an in-memory DAO for the different entities to help with quick and easy testing
- [x] Create a factory for initializing the different DAO entities and switching between them based on the environment

### Acceptance criteria
* All existing behavior is reproducible even when using the in-memory database implementation.
