### ISSUE TITLE
Upgrade to react-scripts@5.0.0 and storybook@6.4.13 to remove security vulnerabilities

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#153]
### Context
There are a number of security vulnerabilities related to older versions of _node-forge_ and _immer_ being used due to react-scripts and storybook/react having transitive dependencies on them. Thankfully, react-scripts have released v5.0.0 and storybook have release 6.4.13 to resolve these issues. So we need to upgrade to those versions to remove the vulnerable versions of the affected packages.

### Tasks
- [ ] Upgrade react-scripts to 5.0.0 (this is the next available version after out current 4.0.3)
- [ ] Upgrade storybook to 6.4.13
- [ ] Check how many additional security vulnerabilities are patched due to these upgrades.
- [ ] Verify app and storybook functionality still works
- [ ] Verify that the security vulnerabilities are resolved after merging.

### Acceptance criteria
* The immer and node-forge vulnerabilities are resolved and there are no issues with running the app or the storybook.
