### ISSUE TITLE
Enhance Add Player Form to allow player image upload.

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#162]
## Tasks
- [ ] Integrate the file upload widget with the player creation form.
- [ ] Update the add player resource and service to store the file key representing the player image
- [ ] (optional) Get the club logo file key from the club entity and add it to the player metadata entity.

## Acceptance criteria
* User is able to upload an image to represent the player when creating a new player.
* User can see the uploaded image when loading the player home page in the _Player Bio_ component.
* Unit and API tests have been added/updated to verify the above scenarios.
