### ISSUE TITLE
Create API tests in Insomnia by leveraging the Design Document feature

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#171]
## Context
Currently, all our API tests are in the form of collections that we have to manually run inside Insomnia. Instead, if we create a design document, we can add those collections there (copy/paste in the worst-case scenario) and make assertions on the response.

## Tasks
- [x] Create a design document following [this tutorial](https://betterprogramming.pub/ci-for-apis-with-the-kong-insomnia-cli-and-github-actions-270eba79174d)
- [x] Port the collection requests to the design document
- [x] Write tests and make assertions on the responses
- [x] Add more requests to cover other edge cases.
- [x] Explore running a happy path collection with the help of `insomnia-inso` to preload the JDBI database for easier manual testing.

### Acceptance criteria
* A design document is created in Insomnia with thorough API testing.

**Comment by Spider101** [comment]
I was able to create a test suite with happy path requests that filled up the server database with some seed data. But, it is not possible to use `insomnia-inso` to run them from the terminal because it doesn't have support for plugins, and the requests heavily use the faker plugin. So, the alternative is to manually run the happy path test suite from the desktop app whenever the server is restarted
