### ISSUE TITLE
Add club logo to player metadata and club summary entities

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#172]
## Context
Now that the functionality to add a club logo image to the club entity has been introduced, we can now add the file key representing the image to the player metadata and club summary entities. In this way, we can then display the club logo when viewing the club summary items on the user home page and in the player bio card on the player home page.

## Tasks
- [x] Update the _add_ endpoint for the player resource such that the _clubLogo_ from the club entity is added to the corresponding property on the _Metadata_ entity associated with the player.
- [x] Update the DAO logic for fetching the club summary entity to include the club logo file key as well. Update the API documentation and schema example to reflect the same.
- [ ] Update the club summary item component to show the club logo as well.
- [ ] Integrate the client code with the _GET_ endpoint on the file upload resource to download and display the club logo for the corresponding entities.
- [ ] Update unit and API tests for both server and client code changes.

## Acceptance criteria
* The club logo is displayed as a badge on the club summary item on the user's home page.
* The club logo is displayed in the player bio card component where it is rendered.
