### ISSUE TITLE
Bug Fix: Fix issue with custom tooltip on charts with a single column of data

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#184]
## Context

Currently, the custom tooltip component throws an error when the payload from a chart has a single column (X-axis) of data. Investigate and fix it. The player ability and attribute progress charts seem to be affected by this. The charts might be affected too.

## Tasks

- [x] Figure out the root cause and fix it.
- [x] Verify if other charts are affected and fix them as well.
- [x] Add story(s) mimicking the behavior and add unit tests if possible.

## Acceptance criteria

* Able to load the charts and display the tooltip with the correct information.
