### ISSUE TITLE
Fix issues with the `PlayerBioCard` component.

### ISSUE THREAD

**Issue by Spider101** [Spider101/football-stats-dashboard#186]
## Context

Since the date picker is not implemented on the _AddPlayerForm_ component, we are only allowing the user to input the player's age instead of their full date of birth. As a result, the D.O.B element in the _PlayerBioCard_ component is redundant and erroring out due to the lack of that piece of information.
Additionally, the club logo element is not correctly using the `/file-storage/image/{fileKey}` endpoint to download the club logo image.

## Tasks

- [x] Remove the D.O.B element in the component till the date picker is implemented for the add player form.
- [x] Correctly use the download image endpoint to display the club logo image.
- [ ] Add tests or update stories to verify and track the change.

## Acceptance criteria

* The _PlayerBioCard_ component renders correctly without the date of birth element and with a valid club logo image element.
